spring:
 redis:
   database: 15
   host: 81.68.229.180
   port: 6379
   password: 320316
   timeout: 3000
   #==============redis线程池设置============================================================================================================================
   jedis:
     pool:
       min-idle: 200   # 连接池中的最大空闲连接，默认值也是8。
       max-idle: 200  #连接池中的最小空闲连接，默认值也是0。
       max-active: 2000   # 如果赋值为-1，则表示不限制；pool已经分配了maxActive定义数量的jedis实例，则此时pool的状态为exhausted(耗尽)。
       max-wait: 5000   # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时

