spring:
 redis:
   database: ${redis.database}
   host: ${redis.ip}
   port: ${redis.port}
   password: ${redis.password}
   timeout: ${redis.timeout}
   #==============redis线程池设置============================================================================================================================
   jedis:
     pool:
       min-idle: ${redis.min.idle}   # 连接池中的最大空闲连接，默认值也是8。
       max-idle: ${redis.max.idle}   #连接池中的最小空闲连接，默认值也是0。
       max-active: ${redis.max.active}   # 如果赋值为-1，则表示不限制；pool已经分配了maxActive定义数量的jedis实例，则此时pool的状态为exhausted(耗尽)。
       max-wait: ${redis.max.wait}   # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时

